# Generated by Django 3.1.7 on 2021-06-02 09:50

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='article',
            fields=[
                ('article_id', models.AutoField(primary_key=True, serialize=False)),
                ('comment_date', models.DateTimeField()),
                ('rating', models.FloatField(null=True)),
                ('zan', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='collections',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
    ]
