# Generated by Django 3.1.7 on 2021-06-04 13:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0002_auto_20210602_1759'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='article_title',
            field=models.CharField(default='文章标题', max_length=100),
        ),
        migrations.AddField(
            model_name='article',
            name='cai',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='article',
            name='collection',
            field=models.IntegerField(default=0),
        ),
    ]
