# Generated by Django 3.1.7 on 2021-06-01 09:15

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('games', '0003_auto_20210326_2056'),
        ('comments', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='collections',
            fields=[
                ('collection_id', models.AutoField(primary_key=True, serialize=False)),
                ('game_id', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='games.gameinfo')),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
